/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thaiddd_javaguiex_core_NativeC */

#ifndef _Included_com_thaiddd_javaguiex_core_NativeC
#define _Included_com_thaiddd_javaguiex_core_NativeC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thaiddd_javaguiex_core_NativeC
 * Method:    nativeDecStr
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 * Input:jstring
 * Output:jobjectArray
 * Discrition: This is the String interface, input the hexview string of 8583 message body, get a string arrary as result
 */
JNIEXPORT jobjectArray JNICALL Java_com_thaiddd_javaguiex_core_NativeC_nativeDecStr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_thaiddd_javaguiex_core_NativeC
 * Method:    nativeDecBin
 * Signature: ([B)[[B
 * Input:jbyteArray
 * Output:JobjectArray
 * Discription: This is the binary interface, input the binary data of 8583 message body, get a binary array as result
 */
JNIEXPORT jobjectArray JNICALL Java_com_thaiddd_javaguiex_core_NativeC_nativeDecBin
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
