/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thaiddd_javaguiex_core_Dump */

#ifndef _Included_com_thaiddd_javaguiex_core_Dump
#define _Included_com_thaiddd_javaguiex_core_Dump
#ifdef __cplusplus
extern "C" {
#endif

extern JNIEnv *lenv;
typedef struct{
  jclass classTcpDataBlock;
  jfieldID extraInfo;
  jfieldID ipSrc;
  jfieldID ipDst;
  jfieldID portSrc;
  jfieldID portDst;
  jfieldID dataLen;
  jfieldID data;
}classTcpDataBlock;
typedef struct{
  jclass classNICDevice;
  jmethodID constructor;
  jfieldID name;
  jfieldID description;
  jfieldID addresses;
  jfieldID flags;
}classNICDevice;
typedef struct{
  jclass classString;
}classString;
extern classTcpDataBlock classT;
extern classNICDevice classN;
extern classString classS;

#define CHECKEXPJ(x) \
if((*x)->ExceptionCheck(x)) \
  { \
    printf("Exception begin:\t"  __FILE__ " row %d\n", __LINE__); \
    (*x)->ExceptionDescribe(x); \
    (*x)->ExceptionClear(x); \
    printf("Exception end.\n"); \
    return -1; \
  }

/*
 * Class:     com_thaiddd_javaguiex_core_Dump
 * Method:    devList
 * Signature: ([Lcom/thaiddd/javaguiex/core/NICDevice;)Z
 * Input:no
 * Output:jobjectArray
 * Return:jboolean 1 if sucess, 0 if found 0 device or jobjectArray size too short, -1 if error occured
 */
JNIEXPORT jint JNICALL Java_com_thaiddd_javaguiex_core_Dump_devList
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_thaiddd_javaguiex_core_Dump
 * Method:    openDev
 * Signature: (I)Z
 * Input: jint is the index of devices
 * Output: no
 * Return: 1 if sucess, 0 if index outof range, -1 if error occured
 */
JNIEXPORT jint JNICALL Java_com_thaiddd_javaguiex_core_Dump_openDev
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_thaiddd_javaguiex_core_Dump
 * Method:    setFilter
 * Signature: (Ljava/lang/String;)Z
 * Input:jstring is the filter
 * Output:no
 * Return: 1 if sucess, 0 if filter compile fail, -1 if error occured
 */
JNIEXPORT jint JNICALL Java_com_thaiddd_javaguiex_core_Dump_setFilter
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_thaiddd_javaguiex_core_Dump
 * Method:    loop
 * Signature: (I)Z
 * Input:jnit is loop cnt
 * Output:no
 * Return: 
 */
JNIEXPORT jint JNICALL Java_com_thaiddd_javaguiex_core_Dump_loop
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_thaiddd_javaguiex_core_Dump
 * Method:    readFromUserBuff
 * Signature: (Lcom/thaiddd/javaguiex/core/TcpDataBlock;)I
 */
JNIEXPORT jint JNICALL Java_com_thaiddd_javaguiex_core_Dump_readFromUserBuff
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_thaiddd_javaguiex_core_Dump
 * Method:    stoploop
 * Signature: (I)Z
 * Input:no
 * Output:no
 * Return: jinit
 */
JNIEXPORT jint JNICALL Java_com_thaiddd_javaguiex_core_Dump_stoploop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
